services:
  - type: web
    name: stocksync-ims
    env: docker
    plan: free
    branch: deployment
    dockerCommand: "" # Uses standard ENTRYPOINT from Dockerfile
    envVars:
      - key: APP_NAME
        value: "StockSync IMS"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: "" # Fill in Neon DB Host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: "" # Fill in Neon DB Name
      - key: DB_USERNAME
        value: "" # Fill in Neon DB User
      - key: DB_PASSWORD
        value: "" # Fill in Neon DB Password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: LOG_CHANNEL
        value: stderr
